version: '3.8'
name: gsh
services:
    backend:
        image: backend
        build: .
        ports:
            - '7000:7000'
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - app-network
    db:
        image: mysql:5.7
        container_name: mysql
        env_file:
            - .env
        ports:
            - '3306:3306'
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
